apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1zqc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1zqc
    app.kubernetes.io/part-of: tkrw-pr712-0075-0068-app
  name: devfile-sample-1zqc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1zqc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1zqc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-1zqc@sha256:a9e0c60996e18b350c46c553481374e537e1fdf4c52a39e48e2794fdb3542a1a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
